/**
 * Final role × action matrix (Q12). Single source of truth for docs and generated tests.
 * Presence of an action here without a matching `can()` expectation fails the suite.
 */
import type { AuthzAction } from './actions';
import type { ProjectRole } from '@nexus/contracts';

export type MatrixCell = boolean;

/** Every AuthzAction that is project/work-item scoped must appear here. */
export const PROJECT_SCOPED_ACTIONS = [
  'project.read',
  'project.view_analytics',
  'project.update',
  'project.archive',
  'project.manage_members',
  'project.manage_pipeline',
  'project.manage_labels',
  'project.manage_bindings',
  'project.manage_gates',
  'work_item.read',
  'work_item.create',
  'work_item.update',
  'work_item.transition',
  'work_item.archive',
  'spec.read',
  'spec.write',
  'audit.read',
  'status.override',
  'gate.override',
  'run.read',
  'run.launch',
  'run.cancel',
  'question.answer',
  'approval.decide',
] as const satisfies readonly AuthzAction[];

export type ProjectScopedAction = (typeof PROJECT_SCOPED_ACTIONS)[number];

export const ROLE_MATRIX: Record<
  ProjectRole,
  Record<ProjectScopedAction, MatrixCell>
> = {
  viewer: {
    'project.read': true,
    'project.view_analytics': true,
    'project.update': false,
    'project.archive': false,
    'project.manage_members': false,
    'project.manage_pipeline': false,
    'project.manage_labels': false,
    'project.manage_bindings': false,
    'project.manage_gates': false,
    'work_item.read': true,
    'work_item.create': false,
    'work_item.update': false,
    'work_item.transition': false,
    'work_item.archive': false,
    'spec.read': true,
    'spec.write': false,
    'audit.read': true,
    'status.override': false,
    'gate.override': false,
    'run.read': true,
    'run.launch': false,
    'run.cancel': false,
    'question.answer': false,
    'approval.decide': false,
  },
  member: {
    'project.read': true,
    'project.view_analytics': true,
    'project.update': false,
    'project.archive': false,
    'project.manage_members': false,
    'project.manage_pipeline': false,
    'project.manage_labels': false,
    'project.manage_bindings': false,
    'project.manage_gates': false,
    'work_item.read': true,
    'work_item.create': true,
    'work_item.update': true,
    'work_item.transition': true,
    'work_item.archive': false,
    'spec.read': true,
    'spec.write': true,
    'audit.read': true,
    'status.override': false,
    'gate.override': false,
    'run.read': true,
    'run.launch': true,
    'run.cancel': true,
    'question.answer': true,
    'approval.decide': true,
  },
  maintainer: {
    'project.read': true,
    'project.view_analytics': true,
    'project.update': true,
    'project.archive': false,
    'project.manage_members': true,
    'project.manage_pipeline': true,
    'project.manage_labels': true,
    'project.manage_bindings': true,
    'project.manage_gates': true,
    'work_item.read': true,
    'work_item.create': true,
    'work_item.update': true,
    'work_item.transition': true,
    'work_item.archive': true,
    'spec.read': true,
    'spec.write': true,
    'audit.read': true,
    'status.override': true,
    'gate.override': true,
    'run.read': true,
    'run.launch': true,
    'run.cancel': true,
    'question.answer': true,
    'approval.decide': true,
  },
  owner: {
    'project.read': true,
    'project.view_analytics': true,
    'project.update': true,
    'project.archive': true,
    'project.manage_members': true,
    'project.manage_pipeline': true,
    'project.manage_labels': true,
    'project.manage_bindings': true,
    'project.manage_gates': true,
    'work_item.read': true,
    'work_item.create': true,
    'work_item.update': true,
    'work_item.transition': true,
    'work_item.archive': true,
    'spec.read': true,
    'spec.write': true,
    'audit.read': true,
    'status.override': true,
    'gate.override': true,
    'run.read': true,
    'run.launch': true,
    'run.cancel': true,
    'question.answer': true,
    'approval.decide': true,
  },
};
